version: '3.5'
services:
  database:
    image: mariadb:10.3
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
  app:
    depends_on:
      - database
    build:
      context: .
    image: foodzen-app
    ports:
      - "80:80"
      - "443:443"
    environment:
    - "DATABASE_URL=mysql://db:db@database:3306/db"
    - "CORS_ALLOW_ORIGIN=.*"
    - "SERVERNAME=foodzen.localhost"
