import { Component, OnInit } from "@angular/core";
import {BehaviorSubject, Observable, of, startWith, switchMap} from "rxjs";

import {Meal, MealService} from "../../api/meal";
import {FoodConstraint} from "../../api/food-constraint";
import {FormControl} from "@angular/forms";
import {map} from "rxjs/operators";

@Component({
	selector: "app-meals",
	styleUrls: ["./meals.component.scss"],
	templateUrl: "./meals.component.html"
})
export class MealsComponent implements OnInit {
	public meals$!: Observable<Meal[]>;
	public foodConstraintSearch = new FormControl();
	public filteredFoodConstraints: BehaviorSubject<FoodConstraint[]> = new BehaviorSubject<FoodConstraint[]>([]);
	public addedFoodConstraints: FoodConstraint[] = [];
	public searchTerms: string;
	public minutes = 0;

	public constructor(private mealService: MealService) {
		this.searchTerms = "";
	}

	private _filter(value: string): Observable<FoodConstraint[]> {
		return of( this.serverFoodConstraints
			.filter( fc => fc.name.toLowerCase().includes(value.toLowerCase()) )
		);
	}

	public ngOnInit(): void {
		// subscribe to observables here (use "extends BaseComponent") et appeler addSubscription()
		this.meals$ = of([
			{
				"id": 1,
				"name":"Spaghetti carbonara",
				"description": "Les pâtes à la carbonara ou sauce carbonara1 (pasta alla carbonara, en italien) sont une spécialité " +
					"culinaire traditionnelle de la cuisine italienne, originaire de Rome et du Latium, très populaire en " +
					"Italie et dans le monde, à base de pâtes cuisinées avec des œufs, des lardons et du fromage râpé."
			},

			{
				"id": 2,
				"name":"Pad thai",
				"description": "Le phat thai est un plat traditionnel thaïlandais à base de nouilles de riz, très apprécié et très " +
					"consommé dans toute la Thaïlande. Son nom signifie littéralement « sauté de style thaï ». "
			}

		] as Meal[]);

		this.foodConstraintSearch.valueChanges.pipe(
			startWith(""),
			map(value => (typeof value === "string" ? value : value.name)),
			switchMap(value => this._filter(value))
		).subscribe(x => this.filteredFoodConstraints.next(x));
    }

	public displayWith(foodConstraint: FoodConstraint) : string {
		return foodConstraint.name;
	}

	// if instant search is wanted -> https://angular.io/tutorial/toh-pt6#the-searchterms-rxjs-subject
	public launchSearch(): void {
		this.mealService.get(0); // searchTerms
	}
	public chosenFoodConstraints:FoodConstraint[] = [];
	public serverFoodConstraints = [
		{"id": 1, "name": "Cacahuètes Grillées", "description": ""},
		{"id": 2, "name": "Nature", "description": ""},
		{"id": 3, "name": "Graisse Butyrique", "description": ""},
		{"id": 4, "name": "Nordhavsrâkor", "description": ""},
		{"id": 5, "name": "Lactate", "description": ""},
		{"id": 6, "name": "Glaçage Au Chocolat 20 % :", "description": ""},
		{"id": 7, "name": "Buttermilchpulver", "description": ""},
		{"id": 8, "name": "Foie De Morue", "description": ""},
		{"id": 9, "name": "Şoja", "description": ""},
		{"id": 10, "name": "Sauce Aigre Douce 20G :", "description": ""},
		{"id": 11, "name": "Carraghénanes", "description": ""},
		{"id": 12, "name": "Almidon De Trigo", "description": ""},
		{"id": 13, "name": "Lait Écrémé Réhydraté Eau Sirop De Glucose Sucre Graisse De Coprah Cacao Maigre En Poudre Lactose", "description": ""},
		{"id": 14, "name": "Prot", "description": ""},
		{"id": 15, "name": "Maïs", "description": ""},
		{"id": 16, "name": "Noixdecajou", "description": ""},
		{"id": 17, "name": "Huevo", "description": ""},
		{"id": 18, "name": "Beurre Doux", "description": ""},
		{"id": 19, "name": "Préparation De Fromage Fondu", "description": ""},
		{"id": 20, "name": "Orge Maltée", "description": ""},
		{"id": 21, "name": "Poivron Rouge 4 %", "description": ""},
		{"id": 22, "name": "Fruit À Coque Oeuf", "description": ""},
		{"id": 23, "name": "Mandarine", "description": ""},
		{"id": 24, "name": "Frischkäse", "description": ""},
		{"id": 25, "name": "Hostie", "description": ""},
		{"id": 26, "name": "Œufs De Cabillaud", "description": ""},
		{"id": 27, "name": "Thé Vert Au Jasmin :", "description": ""},
		{"id": 28, "name": "Sarrasin", "description": ""},
		{"id": 29, "name": "Crevettes À La Noix De Coco", "description": ""},
		{"id": 30, "name": "Décors :", "description": ""},
		{"id": 31, "name": "Saumon Argenté Du Pacifique 9 %", "description": ""},
		{"id": 32, "name": "Tofu Soyeux", "description": ""},
		{"id": 33, "name": "Merlan Bleu", "description": ""},
		{"id": 34, "name": "Truite Arc En Ciel", "description": ""},
		{"id": 35, "name": "Flocon D’Avoine", "description": ""},
		{"id": 36, "name": "Gs1:T4078:Ax", "description": ""},
		{"id": 37, "name": "Dérivés", "description": ""},
		{"id": 38, "name": "Châtaigne", "description": ""},
		{"id": 39, "name": "Malté", "description": ""},
		{"id": 40, "name": "Céréales", "description": ""},
		{"id": 41, "name": "Clupea Harengus", "description": ""},
		{"id": 42, "name": "Étrilles", "description": ""},
		{"id": 43, "name": "Anhydre Sulfureux", "description": ""},
		{"id": 44, "name": "Gras", "description": ""},
		{"id": 45, "name": "Nata", "description": ""},
		{"id": 46, "name": "Pâtes", "description": ""},
		{"id": 47, "name": "Vénus", "description": ""},
		{"id": 48, "name": "Malt De Blé", "description": ""},
		{"id": 49, "name": "Lingue", "description": ""},
		{"id": 50, "name": "Metabisulfito", "description": ""},
		{"id": 51, "name": "Eau", "description": ""},
		{"id": 52, "name": "Calamares", "description": ""},
		{"id": 53, "name": "Ingrédients Issus De L'Agriculture Biologique", "description": ""},
		{"id": 54, "name": "Crème Glacée Chocolat", "description": ""},
		{"id": 55, "name": "Soja Précuit", "description": ""},
		{"id": 56, "name": "Sahnepulver", "description": ""},
		{"id": 57, "name": "Pâte À Pizza", "description": ""},
		{"id": 58, "name": "Láctico", "description": ""},
		{"id": 59, "name": "Yogourt", "description": ""},
		{"id": 60, "name": "Mozzarelle", "description": ""},
		{"id": 61, "name": "Grana Padano Aop", "description": ""},
		{"id": 62, "name": "Spécialité Fromagère", "description": ""},
		{"id": 63, "name": "Biscuits Salés Goût Pizza", "description": ""},
		{"id": 64, "name": "Raclette Aux Trois Poivres:Lait", "description": ""},
		{"id": 65, "name": "Blé Lactose", "description": ""},
		{"id": 66, "name": "Graisses Végétales", "description": ""},
		{"id": 67, "name": "Sauce Burger 85G Ingrédients :", "description": ""},
		{"id": 68, "name": "Les Personnes Qui Sont Allergiques Aux Mollusques Et Crustacés Et/Ou Auxacariens Peuvent Avoir Une Réactionallergique À La Consommationd'Insectes.", "description": ""},
		{"id": 69, "name": "Gs1:T4078:Eg", "description": ""},
		{"id": 70, "name": "Caféine", "description": ""},
		{"id": 71, "name": "Maguereau", "description": ""},
		{"id": 72, "name": "Sésame Complet", "description": ""},
		{"id": 73, "name": "Graines De Tournesol", "description": ""},
		{"id": 74, "name": "Crème De Lactosérum", "description": ""},
		{"id": 75, "name": "Perles De Blé (Gluten)", "description": ""},
		{"id": 76, "name": "Maasdam", "description": ""},
		{"id": 77, "name": "Gélifiant : Carraghénanes. Pourcentages Exprimés Sur Le Produit Fini. Certains Ingrédients De Ce Produit Ne Proviennent Pas De France.", "description": ""},
		{"id": 78, "name": "Nosiettes", "description": ""},
		{"id": 79, "name": "Beurre De Cacahuètes", "description": ""},
		{"id": 80, "name": "Thon Germon", "description": ""},
		{"id": 81, "name": "Metton", "description": ""},
		{"id": 82, "name": "Lait Crème", "description": ""},
		{"id": 83, "name": "Maltodextrine De Blé", "description": ""},
		{"id": 84, "name": "Parmigiano Regiano", "description": ""},
		{"id": 85, "name": "Chair De Crevette", "description": ""},
		{"id": 86, "name": "Métabisulfite De Sodium", "description": ""},
		{"id": 87, "name": "Sirop De Glucose Fructose", "description": ""},
		{"id": 88, "name": "Glute", "description": ""},
		{"id": 89, "name": "Citron Vert", "description": ""},
		{"id": 90, "name": "Lactoséum", "description": ""},
		{"id": 91, "name": "Lapte", "description": ""},
		{"id": 92, "name": "Filetage", "description": ""},
		{"id": 93, "name": "Clémentine", "description": ""},
		{"id": 94, "name": "Beuure", "description": ""},
		{"id": 95, "name": "Mjólktrdufl", "description": ""},
		{"id": 96, "name": "Néant", "description": ""},
		{"id": 97, "name": "Gasoil", "description": ""},
		{"id": 98, "name": "Pressure", "description": ""},
		{"id": 99, "name": "Ales", "description": ""},
		{"id": 100, "name": "Glace Parfum Vanille 78 % : Lactose", "description": ""},
		{"id": 101, "name": "Thon Albacore", "description": ""},
		{"id": 102, "name": "Imazalil", "description": ""},
		{"id": 103, "name": "Lactée", "description": ""},
		{"id": 104, "name": "Épeautre De Tartarie", "description": ""},
		{"id": 105, "name": "Gluten De Froment", "description": ""},
		{"id": 106, "name": "Allergènes Présents : Poissons", "description": ""},
		{"id": 107, "name": "Céréales Chocolatées Avec Un Fourrage Goût Chocolat :", "description": ""},
		{"id": 108, "name": "Crevettes Au Curry Thaï Vert", "description": ""},
		{"id": 109, "name": "Sauce Moutarde À L'Ancienne 12 % :", "description": ""},
		{"id": 110, "name": "Blé Lait Emmental Mozzarella Fromage", "description": ""},
		{"id": 111, "name": "Noic Du Brésil", "description": ""},
		{"id": 112, "name": "Pekannusskernstücke", "description": ""},
		{"id": 113, "name": "Protéines Solubles", "description": ""},
		{"id": 114, "name": "Abricots", "description": ""},
		{"id": 115, "name": "Ferments Lactiques Et D'Affinage", "description": ""},
		{"id": 116, "name": "Palme", "description": ""},
		{"id": 117, "name": "Seitan De Blé", "description": ""},
		{"id": 118, "name": "Hühnerei Trockeneiweiß", "description": ""},
		{"id": 119, "name": "Rhum", "description": ""},
		{"id": 120, "name": "Lotte", "description": ""},
		{"id": 121, "name": "Nems Au Porc 4X65G :", "description": ""},
		{"id": 122, "name": "Pesto", "description": ""},
		{"id": 123, "name": "Emmenthal", "description": ""},
		{"id": 124, "name": "Alune", "description": ""},
		{"id": 125, "name": "Crystacé", "description": ""},
		{"id": 126, "name": "Abricot", "description": ""},
		{"id": 127, "name": "Protéines De Lactosérum Du Lait De Brebis", "description": ""},
		{"id": 128, "name": "Riz", "description": ""},
		{"id": 129, "name": "Pamplemousse", "description": ""},
		{"id": 130, "name": "Chocolat Blanc :", "description": ""},
		{"id": 131, "name": "Leche", "description": ""},
		{"id": 132, "name": "Semoule", "description": ""},
		{"id": 133, "name": "Blé Malté", "description": ""},
		{"id": 134, "name": "Matière Grasse Laitière", "description": ""},
		{"id": 135, "name": "Protéines Lactiques", "description": ""},
		{"id": 136, "name": "Chair De Thon", "description": ""},
		{"id": 137, "name": "Dioxyde De Sodium", "description": ""},
		{"id": 138, "name": "Sérum De Iait", "description": ""},
		{"id": 139, "name": "Pau", "description": ""},
		{"id": 140, "name": "Fenilalanina", "description": ""},
		{"id": 141, "name": "Recubrimiento De Chocolate Con Leche 26 %:", "description": ""},
		{"id": 142, "name": "Non Renseigne", "description": ""},
		{"id": 143, "name": "Coquillages", "description": ""},
		{"id": 144, "name": "Farine D'Orge Maltée", "description": ""},
		{"id": 145, "name": "Levains Lactiques", "description": ""},
		{"id": 146, "name": "Lime", "description": ""},
		{"id": 147, "name": "Fromage Poudre Déshydratée", "description": ""},
		{"id": 148, "name": "Vinaigre De Vin Blanc", "description": ""},
		{"id": 149, "name": "Malt Froment", "description": ""},
		{"id": 150, "name": "Conservateur Chimique", "description": ""},
		{"id": 151, "name": "Arôme Vanille", "description": ""},
		{"id": 152, "name": "Moulage De Chocolat Au Lait", "description": ""},
		{"id": 153, "name": "Pecorino Romano Dop", "description": ""},
		{"id": 154, "name": "Loddarom", "description": ""},
		{"id": 155, "name": "Huile De Sésame Vierge", "description": ""},
		{"id": 156, "name": "Traité Contre La Germination", "description": ""},
		{"id": 157, "name": "Extraite", "description": ""},
		{"id": 158, "name": "Fibre D'Avoine", "description": ""},
		{"id": 159, "name": "Ogm", "description": ""},
		{"id": 160, "name": "Eglefin", "description": ""},
		{"id": 161, "name": "Asperge Verte 4 %", "description": ""},
		{"id": 162, "name": "7%", "description": ""},
		{"id": 163, "name": "Sauce Au Basilic 12 % :", "description": ""},
		{"id": 164, "name": "Parmigiano Reggiano Aop", "description": ""},
		{"id": 165, "name": "Huile D'Arachide", "description": ""},
		{"id": 166, "name": "Bisulfite De Potassium", "description": ""},
		{"id": 167, "name": "Ble Poisson Lait Oeuf Moutarde", "description": ""},
		{"id": 168, "name": "Tournesol", "description": ""},
		{"id": 169, "name": "Vers", "description": ""},
		{"id": 170, "name": "Lacté", "description": ""},
		{"id": 171, "name": "Fromagère", "description": ""},
		{"id": 172, "name": "Pienas", "description": ""},
		{"id": 173, "name": "Cornish Clotted Cream", "description": ""},
		{"id": 174, "name": "Praliné", "description": ""},
		{"id": 175, "name": "E220", "description": ""},
		{"id": 176, "name": "Zobene", "description": ""},
		{"id": 177, "name": "Téguments", "description": ""},
		{"id": 178, "name": "Camembert", "description": ""},
		{"id": 179, "name": "Féra", "description": ""},
		{"id": 180, "name": "Faisselle", "description": ""},
		{"id": 181, "name": "Gs1:T4078:Ai", "description": ""},
		{"id": 182, "name": "Soufflés Goût Bacon", "description": ""},
		{"id": 183, "name": "Thé Vert Aromatisé Saveur Fruits Exotiques :", "description": ""},
		{"id": 184, "name": "Vinaigrette Au Vinaigre Balsamique", "description": ""},
		{"id": 185, "name": "Caroube", "description": ""},
		{"id": 186, "name": "Farine De Seigle Complet*", "description": ""},
		{"id": 187, "name": "Alaska", "description": ""},
		{"id": 188, "name": "Pâtes Rouges", "description": ""},
		{"id": 189, "name": "Dessert Lacté Aromatisé Saveur Vanille :", "description": ""},
		{"id": 190, "name": "Penaeus Monodon", "description": ""},
		{"id": 191, "name": "Mozzarella Au Lait De Bufflone", "description": ""},
		{"id": 192, "name": "Weizenkleber", "description": ""},
		{"id": 193, "name": "E385: Interdit En Australie/Dangereux Pour Les Jeunes Enfants/Troubles De La Coagulation Du Sang/Vomissement/Diarrhées/Crampes Abdominales Ou Musculaires Etc.", "description": ""},
		{"id": 194, "name": "Homard Canadien", "description": ""},
		{"id": 195, "name": "Millet", "description": ""},
		{"id": 196, "name": "E223: Troubles Digestifs/Nausées/Contrarie La Vitamine B/Mutagéne/", "description": ""},
		{"id": 197, "name": "Fromage Parmesan", "description": ""},
		{"id": 198, "name": "Sfl", "description": ""},
		{"id": 199, "name": "Surimi", "description": ""},
		{"id": 200, "name": "Orz", "description": ""},
		{"id": 201, "name": "Bigorneau", "description": ""},
		{"id": 202, "name": "Metton", "description": ""},
		{"id": 203, "name": "Farine", "description": ""},
		{"id": 204, "name": "Ténébrions", "description": ""},
		{"id": 205, "name": "Fourrage Au Chocolat 60 % :", "description": ""},
		{"id": 206, "name": "Viii", "description": ""},
		{"id": 207, "name": "Origine Pérou (Ap) Ou Chili (Ac)]", "description": ""},
		{"id": 208, "name": "Huile De Soja", "description": ""},
		{"id": 209, "name": "Fromagère", "description": ""},
		{"id": 210, "name": "Gs1:T4078:Ba", "description": ""},
		{"id": 211, "name": "Crème Glacée Vanille", "description": ""},
		{"id": 212, "name": "Lactés", "description": ""},
		{"id": 213, "name": "Cynoglossus Robustus", "description": ""},
		{"id": 214, "name": "Loco", "description": ""},
		{"id": 215, "name": "Wasabi", "description": ""},
		{"id": 216, "name": "Mini Nem Poulet Aubergines Aromatisé Préfrit 30 % :", "description": ""},
		{"id": 217, "name": "Saint Nectaire", "description": ""},
		{"id": 218, "name": "Albumine De Lait", "description": ""},
		{"id": 219, "name": "Ferments", "description": ""},
		{"id": 220, "name": "Vin", "description": ""},
		{"id": 221, "name": "Ovas", "description": ""},
		{"id": 222, "name": "Sesam Seed", "description": ""},
		{"id": 223, "name": "Erdnussbutter", "description": ""},
		{"id": 224, "name": "Noix De Coco Rapée", "description": ""},
		{"id": 225, "name": "Oléagineux", "description": ""},
		{"id": 226, "name": "Maltodextrine", "description": ""},
		{"id": 227, "name": "Emincés Au Saumon En Sauce:", "description": ""},
		{"id": 228, "name": "Lacteroserum", "description": ""},
		{"id": 229, "name": "Lactorésum", "description": ""},
		{"id": 230, "name": "Grondins", "description": ""},
		{"id": 231, "name": "Lompe", "description": ""},
		{"id": 232, "name": "Stg", "description": ""},
		{"id": 233, "name": "Chips Saveur Bolognaise", "description": ""},
		{"id": 234, "name": "Farine Bise De Blé", "description": ""},
		{"id": 235, "name": "Disulfite De Sodium", "description": ""},
		{"id": 236, "name": "Malt De Blé", "description": ""},
		{"id": 237, "name": "E226", "description": ""},
		{"id": 238, "name": "Huile De Sésame", "description": ""},
		{"id": 239, "name": "Bille De Mozzarella", "description": ""},
		{"id": 240, "name": "Perche", "description": ""},
		{"id": 241, "name": "Salade Composée 88 % :Pâtes", "description": ""},
		{"id": 242, "name": "Blé́", "description": ""},
		{"id": 243, "name": "Fibre D’Avoine Bio Et Sans Gluten", "description": ""},
		{"id": 244, "name": "Harang", "description": ""},
		{"id": 245, "name": "Sojin", "description": ""},
		{"id": 246, "name": "Vetemjöl", "description": ""},
		{"id": 247, "name": "Vin Rouge", "description": ""},
		{"id": 248, "name": "Sahne", "description": ""},
		{"id": 249, "name": "E150B: Caramel De Synthèse", "description": ""},
		{"id": 250, "name": "Chocolat Noir 5 % (Pâte De Cacao", "description": ""},
		{"id": 251, "name": "Enrobage Au Cacao Maigre", "description": ""},
		{"id": 252, "name": "Arches", "description": ""},
		{"id": 253, "name": "Disulfite De Potassium", "description": ""},
		{"id": 254, "name": "Fonte", "description": ""},
		{"id": 255, "name": "8 Tortillas De Blé Ingrédients", "description": ""},
		{"id": 256, "name": "Fromage Emmental", "description": ""},
		{"id": 257, "name": "Peif", "description": ""},
		{"id": 258, "name": "Additifs :", "description": ""},
		{"id": 259, "name": "Flocons D’Avoine Crus Germés*", "description": ""},
		{"id": 260, "name": "Gorgonzole Aop", "description": ""},
		{"id": 261, "name": "Gluten De Trigo", "description": ""},
		{"id": 262, "name": "Pecorino", "description": ""},
		{"id": 263, "name": "Palourdes", "description": ""},
		{"id": 264, "name": "Flocons D'Épautre Complet", "description": ""},
		{"id": 265, "name": "Lait Écrémé En Poudre", "description": ""},
		{"id": 266, "name": "Huile D'Arachide", "description": ""},
		{"id": 267, "name": "Lactique Laitier", "description": ""},
		{"id": 268, "name": "Soufflés Salés", "description": ""},
		{"id": 269, "name": "Levain", "description": ""},
		{"id": 270, "name": "Poissons Blancs", "description": ""},
		{"id": 271, "name": "Cynoglossus Bilineatus", "description": ""},
		{"id": 272, "name": "Arôme De Fromage", "description": ""},
		{"id": 273, "name": "Gs1:T4078:Be", "description": ""},
		{"id": 274, "name": "Lješnjaci", "description": ""},
		{"id": 275, "name": "Lait Écrémé Reconstitué", "description": ""},
		{"id": 276, "name": "Triticale", "description": ""},
		{"id": 277, "name": "Malt De Froment", "description": ""},
		{"id": 278, "name": "Œufs D'Esturgeon", "description": ""},
		{"id": 279, "name": "Vers De Farine Entiers Déshydratés", "description": ""},
		{"id": 280, "name": "Sole Tropicale", "description": ""},
		{"id": 281, "name": "Pâte", "description": ""},
		{"id": 282, "name": "Milchbestandteile", "description": ""},
		{"id": 283, "name": "Pomme Banane", "description": ""},
		{"id": 284, "name": "Melk", "description": ""},
		{"id": 285, "name": "Thon Blanc", "description": ""},
		{"id": 286, "name": "Peautre", "description": ""},
		{"id": 287, "name": "Poudre D’Œufs", "description": ""},
		{"id": 288, "name": "Fraîche", "description": ""},
		{"id": 289, "name": "Gousse De Vanille Épuisée 0", "description": ""},
		{"id": 290, "name": "Biologique", "description": ""},
		{"id": 291, "name": "Butyrique", "description": ""},
		{"id": 292, "name": "Poire", "description": ""},
		{"id": 293, "name": "Moule Du Pacifique", "description": ""},
		{"id": 294, "name": "Blé Gluten De Blé", "description": ""},
		{"id": 295, "name": "Malte D'Orge", "description": ""},
		{"id": 296, "name": "Sojaproteinisolat", "description": ""},
		{"id": 297, "name": "Fibre De Soja", "description": ""},
		{"id": 298, "name": "Goûters Fourrés Ronds Vanille : Ble", "description": ""},
		{"id": 299, "name": "Mou", "description": ""},
		{"id": 300, "name": "Son D'Avoine", "description": ""},
		{"id": 301, "name": "Fumé Au Bois De Conifère De La Forêt Noire", "description": ""},
		{"id": 302, "name": "Usa", "description": ""},
		{"id": 303, "name": "Vinaigre De Vin", "description": ""},
		{"id": 304, "name": "Amande Crue", "description": ""},
		{"id": 305, "name": "Avoine*", "description": ""},
		{"id": 306, "name": "Blé Oeufs Beurre", "description": ""},
		{"id": 307, "name": "Gs1:T4078:Al", "description": ""},
		{"id": 308, "name": "Réglisse", "description": ""},
		{"id": 309, "name": "Gluten De Froment", "description": ""},
		{"id": 310, "name": "Vollei", "description": ""},
		{"id": 311, "name": "Bulots", "description": ""},
		{"id": 312, "name": "Houblon", "description": ""},
		{"id": 313, "name": "Encre De Seiche", "description": ""},
		{"id": 314, "name": "Farine De Anacarde", "description": ""},
		{"id": 315, "name": "Congre", "description": ""},
		{"id": 316, "name": "Kiwi", "description": ""},
		{"id": 317, "name": "Parmigiano", "description": ""},
		{"id": 318, "name": "Samon", "description": ""},
		{"id": 319, "name": "Saumon Salmo Salar", "description": ""},
		{"id": 320, "name": "Jus De Citron 0", "description": ""},
		{"id": 321, "name": "Plomb", "description": ""},
		{"id": 322, "name": "Gs1:T4078:Ca", "description": ""},
		{"id": 323, "name": "Langouste Caraïbe", "description": ""},
		{"id": 324, "name": "Chèvre", "description": ""},
		{"id": 325, "name": "Séré", "description": ""},
		{"id": 326, "name": "Sepia", "description": ""},
		{"id": 327, "name": "Hühnerei Eiweißpulver", "description": ""},
		{"id": 328, "name": "Orge Malté", "description": ""},
		{"id": 329, "name": "Latte", "description": ""},
		{"id": 330, "name": "Fruits", "description": ""},
		{"id": 331, "name": "Sel", "description": ""},
		{"id": 332, "name": "Protéines Lactique", "description": ""},
		{"id": 333, "name": "Non", "description": ""},
		{"id": 334, "name": "4%", "description": ""},
		{"id": 335, "name": "Lysozyme", "description": ""},
		{"id": 336, "name": "Carraghénanes.", "description": ""},
		{"id": 337, "name": "Champignons", "description": ""},
		{"id": 338, "name": "Séré", "description": ""},
		{"id": 339, "name": "Dorade Sébaste", "description": ""},
		{"id": 340, "name": "Cafeine", "description": ""},
		{"id": 341, "name": "Zola", "description": ""},
		{"id": 342, "name": "Éperlans", "description": ""},
		{"id": 343, "name": "Fromage Cheddar", "description": ""},
		{"id": 344, "name": "Ingrédient :", "description": ""},
		{"id": 345, "name": "Thon Listao", "description": ""},
		{"id": 346, "name": "Aun", "description": ""},
		{"id": 347, "name": "Bonite Séchée", "description": ""},
		{"id": 348, "name": "Amandes* 5 %", "description": ""},
		{"id": 349, "name": "Coque", "description": ""},
		{"id": 350, "name": "Lait De Montagne", "description": ""},
		{"id": 351, "name": "Programme", "description": ""},
		{"id": 352, "name": "Fts", "description": ""},
		{"id": 353, "name": "Lactose Poudre De Lait", "description": ""},
		{"id": 354, "name": "Malts De Blé", "description": ""},
		{"id": 355, "name": "Non", "description": ""},
		{"id": 356, "name": "Vollkornhafer", "description": ""},
		{"id": 357, "name": "Huile Butyrique", "description": ""},
		{"id": 358, "name": "Lait De Vache Pasteurisé", "description": ""},
		{"id": 359, "name": "Émincés Au Saumon :", "description": ""},
		{"id": 360, "name": "Molkenerzeugnis", "description": ""},
		{"id": 361, "name": "Jaune", "description": ""},
		{"id": 362, "name": "Ferments", "description": ""},
		{"id": 363, "name": "Raženo", "description": ""},
		{"id": 364, "name": "Tout Sauf Noyau Atomique", "description": ""},
		{"id": 365, "name": "Pulpe D'Oignon", "description": ""},
		{"id": 366, "name": "Soufflés Aromatisés Emmental", "description": ""},
		{"id": 367, "name": "Avoine", "description": ""},
		{"id": 368, "name": "Pois Chiche", "description": ""},
		{"id": 369, "name": "Fiskprotein", "description": ""},
		{"id": 370, "name": "Antioxydants : Acide Ascorbique", "description": ""},
		{"id": 371, "name": "Mini Feuilleté Champignons :", "description": ""},
		{"id": 372, "name": "Lactique Laitier", "description": ""},
		{"id": 373, "name": "Thé Vert Aromatisé Saveur Agrumes :", "description": ""},
		{"id": 374, "name": "Grana Padano Dop", "description": ""},
		{"id": 375, "name": "Amandes D'Abricot", "description": ""},
		{"id": 376, "name": "Noisettes Hachées", "description": ""},
		{"id": 377, "name": "Ascorbate De Sodium", "description": ""},
		{"id": 378, "name": "Poudre De Lait Écrémé", "description": ""},
		{"id": 379, "name": "Viande Issues De Bovins Abattus Selon Le Rite Halal Par Un Sacrificateur Professionnel. La Traçabilité Des Viandes Entrant Dans La Composition De Ce Produit Est Vérifiée Par Un Organisme De Contrôle Indépendant.", "description": ""},
		{"id": 380, "name": "Matières Grasses Laitières", "description": ""},
		{"id": 381, "name": "Conservateur : Acide Sorbique", "description": ""},
		{"id": 382, "name": "Vin", "description": ""},
		{"id": 383, "name": "Cantal", "description": ""},
		{"id": 384, "name": "Saucisson Sec Supérieur Aux Noix", "description": ""},
		{"id": 385, "name": "Noix De Coco", "description": ""},
		{"id": 386, "name": "Soufflés À La Cacahuète", "description": ""},
		{"id": 387, "name": "Apricot", "description": ""},
		{"id": 388, "name": "Crème Uht", "description": ""},
		{"id": 389, "name": "Échalote", "description": ""},
		{"id": 390, "name": "Tomate", "description": ""},
		{"id": 391, "name": "Sauce Samouraï 80G Ingrédients :", "description": ""},
		{"id": 392, "name": "Pas D'Intolérance Connue", "description": ""},
		{"id": 393, "name": "Mollusques (Huîtres)", "description": ""},
		{"id": 394, "name": "Sarrasin*", "description": ""},
		{"id": 395, "name": "Ingrédients", "description": ""},
		{"id": 396, "name": "Lait Artificiel", "description": ""},
		{"id": 397, "name": "Kabeljau", "description": ""},
		{"id": 398, "name": "Esturgeons", "description": ""},
		{"id": 399, "name": "Lactase", "description": ""},
		{"id": 400, "name": "Esturgeon", "description": ""},
		{"id": 401, "name": "Moulage De Chocolat Au Lait Extra Fin :", "description": ""},
		{"id": 402, "name": "Test Sur Animaux: Endommagement Des Chromosomes Etc..", "description": ""},
		{"id": 403, "name": "Céphalopodes", "description": ""},
		{"id": 404, "name": "Àggula", "description": ""},
		{"id": 405, "name": "Crème Laitière", "description": ""},
		{"id": 406, "name": "Pâte D'Anchois", "description": ""},
		{"id": 407, "name": "Scargots", "description": ""},
		{"id": 408, "name": "Gs1:T4078:Bp", "description": ""},
		{"id": 409, "name": "Cohana", "description": ""},
		{"id": 410, "name": "Ingrédients :", "description": ""},
		{"id": 411, "name": "Encornet Géant", "description": ""},
		{"id": 412, "name": "Oignon Rouge 5 %", "description": ""},
		{"id": 413, "name": "Leche Entera En Polvo", "description": ""},
		{"id": 414, "name": "Disulﬁte De Sodium", "description": ""},
		{"id": 415, "name": "Surimi", "description": ""},
		{"id": 416, "name": "Lalt", "description": ""},
		{"id": 417, "name": "Fromage Frais Saveur Abricot : Lait", "description": ""},
		{"id": 418, "name": "Œufs Entiers En Poudre", "description": ""},
		{"id": 419, "name": "Disufite", "description": ""},
		{"id": 420, "name": "Gruyère Aop", "description": ""},
		{"id": 421, "name": "Oursin", "description": ""},
		{"id": 422, "name": "Colin Lieu", "description": ""},
		{"id": 423, "name": "Sauce Nuoc Mâm 2 X 20 G", "description": ""},
		{"id": 424, "name": "Buttermilk Powder", "description": ""},
		{"id": 425, "name": "Volleipulver", "description": ""},
		{"id": 426, "name": "Emrobage À Base De Cire De Carnauba Et Shellac", "description": ""},
		{"id": 427, "name": "Rouget Barbet", "description": ""},
		{"id": 428, "name": "Dluo", "description": ""},
		{"id": 429, "name": "Sésame 2 %", "description": ""},
		{"id": 430, "name": "Trigo", "description": ""},
		{"id": 431, "name": "Salycilés", "description": ""},
		{"id": 432, "name": "Lait De Soja", "description": ""},
		{"id": 433, "name": "Protéine Lactique", "description": ""},
		{"id": 434, "name": "Lait Cannelle", "description": ""},
		{"id": 435, "name": "Poisson (Anchois) Et Sulfites.", "description": ""},
		{"id": 436, "name": "Écrémé", "description": ""},
		{"id": 437, "name": "Correcteur D Acidité : Acide Citrique", "description": ""},
		{"id": 438, "name": "Petit Lait Doux En Poudre", "description": ""},
		{"id": 439, "name": "Jaunes D'Oeufs En Poudre", "description": ""},
		{"id": 440, "name": "Lait Écrémé Concentré", "description": ""},
		{"id": 441, "name": "Cynoglossus Itinus", "description": ""},
		{"id": 442, "name": "Margarine", "description": ""},
		{"id": 443, "name": "Amidonnier", "description": ""},
		{"id": 444, "name": "Sojin", "description": ""},
		{"id": 445, "name": "Dioxyde De Soufre", "description": ""},
		{"id": 446, "name": "Espadon", "description": ""},
		{"id": 447, "name": "Weizenflakes", "description": ""},
		{"id": 448, "name": "Fromage Frais Saveur Fraise :Lait", "description": ""},
		{"id": 449, "name": "Ferments Tactiques", "description": ""},
		{"id": 450, "name": "Cerises", "description": ""},
		{"id": 451, "name": "Acide", "description": ""},
		{"id": 452, "name": "Suflites", "description": ""},
		{"id": 453, "name": "Basilic", "description": ""},
		{"id": 454, "name": "Préparation Lactée", "description": ""},
		{"id": 455, "name": "Couteaux", "description": ""},
		{"id": 456, "name": "Lácteo", "description": ""},
		{"id": 457, "name": "Lactate", "description": ""},
		{"id": 458, "name": "Salade Composée", "description": ""},
		{"id": 459, "name": "Trigo", "description": ""},
		{"id": 460, "name": "Avocat", "description": ""},
		{"id": 461, "name": "4 Purées De Pommes Poires :", "description": ""},
		{"id": 462, "name": "Pirovo", "description": ""},
		{"id": 463, "name": "Extrait De Carthame", "description": ""},
		{"id": 464, "name": "Dur", "description": ""},
		{"id": 465, "name": "Icc", "description": ""},
		{"id": 466, "name": "Crem", "description": ""},
		{"id": 467, "name": "Sauce Soja Tamari", "description": ""},
		{"id": 468, "name": "Thym. Certains Ingrédients De Ce Produit Ne Proviennent Pas De France", "description": ""},
		{"id": 469, "name": "Margarine", "description": ""},
		{"id": 470, "name": "Diméthylpolysiloxane: E900", "description": ""},
		{"id": 471, "name": "Beaufort", "description": ""},
		{"id": 472, "name": "Éperlans", "description": ""},
		{"id": 473, "name": "Burro", "description": ""},
		{"id": 474, "name": "Anhydride Sulfureux E220", "description": ""},
		{"id": 475, "name": "Milcheiweiße", "description": ""},
		{"id": 476, "name": "Alcool", "description": ""},
		{"id": 477, "name": "Yogourt", "description": ""},
		{"id": 478, "name": "Mutagènes", "description": ""},
		{"id": 479, "name": "Graine De Coriandre", "description": ""},
		{"id": 480, "name": "Pignons", "description": ""},
		{"id": 481, "name": "Amidon De Tapioca", "description": ""},
		{"id": 482, "name": "Fabriqué Dans Un Atelier", "description": ""},
		{"id": 483, "name": "Weizensirup", "description": ""},
		{"id": 484, "name": "Fruits A Coques (Amandes", "description": ""},
		{"id": 485, "name": "Thym", "description": ""},
		{"id": 486, "name": "Noix D'Amazonie", "description": ""},
		{"id": 487, "name": "Gadus Morhua", "description": ""},
		{"id": 488, "name": "Crème Glacée Fraise", "description": ""},
		{"id": 489, "name": "Salami Italien 34 % 5 Tranches", "description": ""},
		{"id": 490, "name": "Romatique", "description": ""},
		{"id": 491, "name": "Milchmineralien", "description": ""},
		{"id": 492, "name": "Œuf Entier", "description": ""},
		{"id": 493, "name": "Gruaux Complets De Seigle", "description": ""},
		{"id": 494, "name": "Vermouth", "description": ""},
		{"id": 495, "name": "E220:", "description": ""},
		{"id": 496, "name": "Éclats Denoisettes", "description": ""},
		{"id": 497, "name": "Fromage Bleu", "description": ""},
		{"id": 498, "name": "Whole Milk Powder", "description": ""},
		{"id": 499, "name": "Amandes Douces", "description": ""},
		{"id": 500, "name": "Éperlan", "description": ""},
		{"id": 501, "name": "Soufflés Salés :", "description": ""},
		{"id": 502, "name": "Eigle", "description": ""},
		{"id": 503, "name": "Antioxydant : E304", "description": ""},
		{"id": 504, "name": "Noisette Blanchie", "description": ""},
		{"id": 505, "name": "Inates", "description": ""},
		{"id": 506, "name": "Schabziger", "description": ""},
		{"id": 507, "name": "Sérum De Lait De Vache", "description": ""},
		{"id": 508, "name": "Magermilchpulver", "description": ""},
		{"id": 509, "name": "Pangas", "description": ""},
		{"id": 510, "name": "Polyphosphates", "description": ""},
		{"id": 511, "name": "Pancetta 34 % 4 Tranches :", "description": ""},
		{"id": 512, "name": "Lactosa", "description": ""},
		{"id": 513, "name": "Avoine", "description": ""},
		{"id": 514, "name": "Cuivre Chaud", "description": ""},
		{"id": 515, "name": "Beuure 10 %", "description": ""},
		{"id": 516, "name": "Bulots", "description": ""},
		{"id": 517, "name": "Huile De Coco", "description": ""},
		{"id": 518, "name": "Gs1:T4078:Hy", "description": ""},
		{"id": 519, "name": "Vers De Farine Comestibles Déshydratés", "description": ""},
		{"id": 520, "name": "Algue", "description": ""},
		{"id": 521, "name": "3 Tartelettes Façon Quiche Lorraine 20 % :", "description": ""},
		{"id": 522, "name": "Marlin", "description": ""},
		{"id": 523, "name": "Calmar Géant", "description": ""},
		{"id": 524, "name": "Sardinelles", "description": ""},
		{"id": 525, "name": "Acariens", "description": ""},
		{"id": 526, "name": "Arômes", "description": ""},
		{"id": 527, "name": "5 Canapés Au Fromage De Chèvre", "description": ""},
		{"id": 528, "name": "Gs1:T4078:St", "description": ""},
		{"id": 529, "name": "Coques", "description": ""},
		{"id": 530, "name": "Cas", "description": ""},
		{"id": 531, "name": "Muscade", "description": ""},
		{"id": 532, "name": "Sojalécithine", "description": ""},
		{"id": 533, "name": "Emmenatl", "description": ""},
		{"id": 534, "name": "Sojaproteinkonzentrat", "description": ""},
		{"id": 535, "name": "Asc", "description": ""},
		{"id": 536, "name": "Curry", "description": ""},
		{"id": 537, "name": "Abricots", "description": ""},
		{"id": 538, "name": "Bl2", "description": ""},
		{"id": 539, "name": "Abricot", "description": ""},
		{"id": 540, "name": "Contient Du Gluten (Avoine)", "description": ""},
		{"id": 541, "name": "Lait Entier Fermenté", "description": ""},
		{"id": 542, "name": "Trigo (Gluten)", "description": ""},
		{"id": 543, "name": "Décor De Confiserie Coloré :", "description": ""},
		{"id": 544, "name": "Sulphate", "description": ""},
		{"id": 545, "name": "Crevettes À La Noix De Coco :Crevette", "description": ""},
		{"id": 546, "name": "Rave", "description": ""},
		{"id": 547, "name": "Tourteau", "description": ""},
		{"id": 548, "name": "Crème Liquide", "description": ""},
		{"id": 549, "name": "Grondin", "description": ""},
		{"id": 550, "name": "Same", "description": ""},
		{"id": 551, "name": "Crustracés", "description": ""},
		{"id": 552, "name": "Levure", "description": ""},
		{"id": 553, "name": "Encornets Géants", "description": ""},
		{"id": 554, "name": "Salicoque Rouge D'Argentine", "description": ""},
		{"id": 555, "name": "Anchois Lactique Laitier", "description": ""},
		{"id": 556, "name": "Clementine", "description": ""},
		{"id": 557, "name": "Saumonette", "description": ""},
		{"id": 558, "name": "Transparence", "description": ""},
		{"id": 559, "name": "Citrus", "description": ""},
		{"id": 560, "name": "Semoule De Blé", "description": ""},
		{"id": 561, "name": "Natriummetabisulfit", "description": ""},
		{"id": 562, "name": "Protéines De Soja", "description": ""},
		{"id": 563, "name": "Lait Et Rpodutis À Base De Lait", "description": ""},
		{"id": 564, "name": "Fenilalanina", "description": ""},
		{"id": 565, "name": "Lompe", "description": ""},
		{"id": 566, "name": "Lešnik", "description": ""},
		{"id": 567, "name": "Crêpe", "description": ""},
		{"id": 568, "name": "Mandeln", "description": ""},
		{"id": 569, "name": "Coques", "description": ""},
		{"id": 570, "name": "Thon Fumé", "description": ""},
		{"id": 571, "name": "Roomkaas", "description": ""},
		{"id": 572, "name": "Semoule De Blé Dur", "description": ""},
		{"id": 573, "name": "Milchserumkonzentrat", "description": ""},
		{"id": 574, "name": "Merlu Blanc Du Cap", "description": ""},
		{"id": 575, "name": "Plie", "description": ""},
		{"id": 576, "name": "Bonito", "description": ""},
		{"id": 577, "name": "Pangasius", "description": ""},
		{"id": 578, "name": "Extrait De Poivre", "description": ""},
		{"id": 579, "name": "Farine Complète", "description": ""},
		{"id": 580, "name": "Blé Noir", "description": ""},
		{"id": 581, "name": "Lactoproteines", "description": ""},
		{"id": 582, "name": "Disufite De Sodium", "description": ""},
		{"id": 583, "name": "Colin Lieu", "description": ""},
		{"id": 584, "name": "Fromage Parmesan", "description": ""},
		{"id": 585, "name": "Crabe Tourteau", "description": ""},
		{"id": 586, "name": "Fromage Edam", "description": ""},
		{"id": 587, "name": "E621", "description": ""},
		{"id": 588, "name": "Merlu Blanc", "description": ""},
		{"id": 589, "name": "Cornflakes", "description": ""},
		{"id": 590, "name": "Dioxyde De Sulfure", "description": ""},
		{"id": 591, "name": "Ingrédients Du Bouillon Déshydraté :", "description": ""},
		{"id": 592, "name": "Mlijeko", "description": ""},
		{"id": 593, "name": "Mourtarde", "description": ""},
		{"id": 594, "name": "Épeautre Complet Égrugé*", "description": ""},
		{"id": 595, "name": "Thon Albacore", "description": ""},
		{"id": 596, "name": "Lait Entier En Poudre", "description": ""},
		{"id": 597, "name": "Blé Huile De Sésame", "description": ""},
		{"id": 598, "name": "Beurre Salé", "description": ""},
		{"id": 599, "name": "L:Ait", "description": ""},
		{"id": 600, "name": "Sulﬁtes", "description": ""},
		{"id": 601, "name": "Samoussas Bœuf 4X50 G", "description": ""},
		{"id": 602, "name": "Arômes Naturels", "description": ""},
		{"id": 603, "name": "Vermicelles", "description": ""},
		{"id": 604, "name": "Fruits À Coques Et Œufs Et Autres Gluten", "description": ""},
		{"id": 605, "name": "C", "description": ""},
		{"id": 606, "name": "Gs1:T4078:Cn", "description": ""},
		{"id": 607, "name": "Graines", "description": ""},
		{"id": 608, "name": "Crustacées", "description": ""},
		{"id": 609, "name": "Mjölkpulver", "description": ""},
		{"id": 610, "name": "Figue", "description": ""},
		{"id": 611, "name": "Crevette Nordique", "description": ""},
		{"id": 612, "name": "Farine Complète", "description": ""},
		{"id": 613, "name": "Noisettes Grillées", "description": ""},
		{"id": 614, "name": "Vii", "description": ""},
		{"id": 615, "name": "Blé Entier", "description": ""},
		{"id": 616, "name": "Fourme D'Ambert", "description": ""},
		{"id": 617, "name": "Farine De Blé 57", "description": ""},
		{"id": 618, "name": "Okara", "description": ""},
		{"id": 619, "name": "Amidons Modifiés De Maïs Et De Pomme De Terre Huile De Tournesol", "description": ""},
		{"id": 620, "name": "Crabe Tourteau", "description": ""},
		{"id": 621, "name": "Gersten Malzextrakt", "description": ""},
		{"id": 622, "name": "Pecorino Romano", "description": ""},
		{"id": 623, "name": "Scamorza", "description": ""},
		{"id": 624, "name": "Ait", "description": ""},
		{"id": 625, "name": "Canelle", "description": ""},
		{"id": 626, "name": "Noix De Coco", "description": ""},
		{"id": 627, "name": "Non Précisé", "description": ""},
		{"id": 628, "name": "Lactose De Lait", "description": ""},
		{"id": 629, "name": "Biscuits Salés Goût Bacon", "description": ""},
		{"id": 630, "name": "Lat", "description": ""},
		{"id": 631, "name": "Fruits Exotiques", "description": ""},
		{"id": 632, "name": "Gerstemout", "description": ""},
		{"id": 633, "name": "Praliné", "description": ""},
		{"id": 634, "name": "Chocolat Noir", "description": ""},
		{"id": 635, "name": "E452", "description": ""},
		{"id": 636, "name": "Allumette Poireaux Saumon :", "description": ""},
		{"id": 637, "name": "Sel De Chlorure D'Ammonium", "description": ""},
		{"id": 638, "name": "Antioxydant: Ascorbate De Sodium. Certains Ingrédients De Ce Produit Ne Proviennent Pas D'Espagne", "description": ""},
		{"id": 639, "name": "Houblon", "description": ""},
		{"id": 640, "name": "Matière Grasse Butyrique", "description": ""},
		{"id": 641, "name": "Châtaignes", "description": ""},
		{"id": 642, "name": "Lait Gluten Soja Moutarde Céleri Oeuf", "description": ""},
		{"id": 643, "name": "Poudre De Lait Entier", "description": ""},
		{"id": 644, "name": "Amende", "description": ""},
		{"id": 645, "name": "Org", "description": ""},
		{"id": 646, "name": "Contient : Blé Seigle Triticale Orge Avoine", "description": ""},
		{"id": 647, "name": "Fruits À Coques (Noisettes)", "description": ""},
		{"id": 648, "name": "Lespersonnes Qui Sont Allergiques Auxmollusques Et Crustacés Et/Ou Auxacariens Peuvent Avoir Une Réactionallergique À La Consommationd'Insectes.", "description": ""},
		{"id": 649, "name": "Disulfite De Sodium", "description": ""},
		{"id": 650, "name": "Nitrate De Potassium", "description": ""},
		{"id": 651, "name": "Parmigianoreggiano", "description": ""},
		{"id": 652, "name": "Beurre Salé", "description": ""},
		{"id": 653, "name": "Atún", "description": ""},
		{"id": 654, "name": "Soufflés À La Tomate :", "description": ""},
		{"id": 655, "name": "Levain", "description": ""},
		{"id": 656, "name": "Raie", "description": ""},
		{"id": 657, "name": "Lait1", "description": ""},
		{"id": 658, "name": "Éclats De Noisettes", "description": ""},
		{"id": 659, "name": "Palourdes", "description": ""},
		{"id": 660, "name": "Malte", "description": ""},
		{"id": 661, "name": "Pêche", "description": ""},
		{"id": 662, "name": "Pralines Aux Amandes", "description": ""},
		{"id": 663, "name": "Tomme", "description": ""},
		{"id": 664, "name": "Protéines", "description": ""},
		{"id": 665, "name": "Échalotes", "description": ""},
		{"id": 666, "name": "Peit Lait", "description": ""},
		{"id": 667, "name": "Gerstenmalzmehl", "description": ""},
		{"id": 668, "name": "Recongeler", "description": ""},
		{"id": 669, "name": "Poudre Delaitécrémé", "description": ""},
		{"id": 670, "name": "Orge De Perle", "description": ""},
		{"id": 671, "name": "Extrait De Malte D'Orge", "description": ""},
		{"id": 672, "name": "D'Épautre", "description": ""},
		{"id": 673, "name": "Chinchard", "description": ""},
		{"id": 674, "name": "Biscuit", "description": ""},
		{"id": 675, "name": "Noyaux D'Abricots", "description": ""},
		{"id": 676, "name": "Mande", "description": ""},
		{"id": 677, "name": "Lait Cacahu Te", "description": ""},
		{"id": 678, "name": "Vinaigrette Allégée En Matières Grasses", "description": ""},
		{"id": 679, "name": "Omelette", "description": ""},
		{"id": 680, "name": "Fruits À Coques (Amandes)", "description": ""},
		{"id": 681, "name": "ŒŒuf", "description": ""},
		{"id": 682, "name": "Torskrom", "description": ""},
		{"id": 683, "name": "Blé; Beurre; Œufs;", "description": ""},
		{"id": 684, "name": "Anhydrides Sulfureux Et Sulftes", "description": ""},
		{"id": 685, "name": "Moutarde De Dijon", "description": ""},
		{"id": 686, "name": "Amande Blanchie", "description": ""},
		{"id": 687, "name": "Amandesmoulues*", "description": ""},
		{"id": 688, "name": "Criquets", "description": ""},
		{"id": 689, "name": "Mozzarrella", "description": ""},
		{"id": 690, "name": "Bien Agiter Avant De Servir. Boire Très Frais. Doit Être Conservé À +6°C Maximum. A Consommer Rapidement Après Ouverture", "description": ""},
		{"id": 691, "name": "Cerfeuil", "description": ""},
		{"id": 692, "name": "Cafeines", "description": ""},
		{"id": 693, "name": "Crème Aigre", "description": ""},
		{"id": 694, "name": "Oeufs Lait", "description": ""},
		{"id": 695, "name": "Protéines Végétales", "description": ""},
		{"id": 696, "name": "Mousse De Foie", "description": ""},
		{"id": 697, "name": "Thé Noir Aromatisé Saveur Bergamote :", "description": ""},
		{"id": 698, "name": "Crème Dessert Au Chocolat", "description": ""},
		{"id": 699, "name": "Truité Fumée", "description": ""},
		{"id": 700, "name": "Weizenprotein", "description": ""},
		{"id": 701, "name": "Iactosèrum", "description": ""},
		{"id": 702, "name": "Beurre D'Amande", "description": ""},
		{"id": 703, "name": "Ce Produit Est Fait À Base De Fruits Ayant Été Traités Avec Des Substances Phytosanitaires ! (Information Reçu De La Part De Lidl.Fr)", "description": ""},
		{"id": 704, "name": "Limande Du Nord", "description": ""},
		{"id": 705, "name": "Entiers", "description": ""},
		{"id": 706, "name": "Reticulatus", "description": ""},
		{"id": 707, "name": "Œufs De Lompe", "description": ""},
		{"id": 708, "name": "Fromage Mascarpone", "description": ""},
		{"id": 709, "name": "Carrelet", "description": ""},
		{"id": 710, "name": "Insomnies Hyperactivité", "description": ""},
		{"id": 711, "name": "Matière Grasse Laitière Anhydre", "description": ""},
		{"id": 712, "name": "Sauce", "description": ""},
		{"id": 713, "name": "Vache", "description": ""},
		{"id": 714, "name": "Présence Possible De Poisson Et De Protéines De Lait.", "description": ""},
		{"id": 715, "name": "Fenugrec", "description": ""},
		{"id": 716, "name": "Tomate 3 %", "description": ""},
		{"id": 717, "name": "Maasdam", "description": ""},
		{"id": 718, "name": "Voine", "description": ""},
		{"id": 719, "name": "Morceaux De Tentacule", "description": ""},
		{"id": 720, "name": "Petit Lait Doux", "description": ""},
		{"id": 721, "name": "Fromage De Lait De Vache Pasteurisé", "description": ""},
		{"id": 722, "name": "Blé Oeufs", "description": ""},
		{"id": 723, "name": "Fromage Grana Padano", "description": ""},
		{"id": 724, "name": "Sojalesitin", "description": ""},
		{"id": 725, "name": "Sauce Poivre 85G Ingrédients :", "description": ""},
		{"id": 726, "name": "Poivron Rouge", "description": ""},
		{"id": 727, "name": "Levure De Bière", "description": ""},
		{"id": 728, "name": "Tome Fraîche", "description": ""},
		{"id": 729, "name": "Maroilles", "description": ""},
		{"id": 730, "name": "Protéines De Blé", "description": ""},
		{"id": 731, "name": "Amandon", "description": ""},
		{"id": 732, "name": "So2", "description": ""},
		{"id": 733, "name": "Glace Vanille Chocolat Au Lait :", "description": ""},
		{"id": 734, "name": "Cerneaux De Noix", "description": ""},
		{"id": 735, "name": "Alit", "description": ""},
		{"id": 736, "name": "Semoule De Blé (Gluten)", "description": ""},
		{"id": 737, "name": "Crème Uht", "description": ""},
		{"id": 738, "name": "Blé (Gluten) Et Soya.", "description": ""},
		{"id": 739, "name": "Lactorésum En Poudre", "description": ""},
		{"id": 740, "name": "Decongele", "description": ""},
		{"id": 741, "name": "Fécule", "description": ""},
		{"id": 742, "name": "Lespersonnes Qui Sont Allergiques Auxmollusques Et Crustacés Et/Ou Auxacariens Peuvent Avoir Une Réactionallergique À La Consommationd'Insectes.", "description": ""},
		{"id": 743, "name": "Crème En Poudre", "description": ""},
		{"id": 744, "name": "Gluten De Blé Beurre", "description": ""},
		{"id": 745, "name": "34", "description": ""},
		{"id": 746, "name": "E440", "description": ""},
		{"id": 747, "name": "Jacques", "description": ""},
		{"id": 748, "name": "Vache", "description": ""},
		{"id": 749, "name": "Beurre Laitier", "description": ""},
		{"id": 750, "name": "Albumine D'Oeuf", "description": ""},
		{"id": 751, "name": "Barley Malt", "description": ""},
		{"id": 752, "name": "Pâtes Alimentaires", "description": ""},
		{"id": 753, "name": "Levures", "description": ""},
		{"id": 754, "name": "Weizeneiweiß", "description": ""},
		{"id": 755, "name": "Mjölkproteiner", "description": ""},
		{"id": 756, "name": "Filets De Maquereaux", "description": ""},
		{"id": 757, "name": "Présence : Crustacé", "description": ""},
		{"id": 758, "name": "E224", "description": ""},
		{"id": 759, "name": "Lacriques", "description": ""},
		{"id": 760, "name": "Ferments.", "description": ""},
		{"id": 761, "name": "Fruit De La Passion", "description": ""},
		{"id": 762, "name": "Beure", "description": ""},
		{"id": 763, "name": "Biscuit Spéculoos", "description": ""},
		{"id": 764, "name": "Pescadilla", "description": ""},
		{"id": 765, "name": "Lysozyme", "description": ""},
		{"id": 766, "name": "Beurre 0.9", "description": ""},
		{"id": 767, "name": "Semoule De Blé Dur", "description": ""},
		{"id": 768, "name": "Lactic", "description": ""},
		{"id": 769, "name": "Dextrose", "description": ""},
		{"id": 770, "name": "Penaeus Vannamei", "description": ""},
		{"id": 771, "name": "Pet", "description": ""},
		{"id": 772, "name": "Thunnus Albacares", "description": ""}
	] as FoodConstraint[];
}
